#!/usr/bin/env python3
"""Regenerate resources/resources.py from resources/resources.qrc (Qt6-safe).

After running, ensures ``from qgis.PyQt import QtCore`` so the plugin loads on
QGIS 3 (Qt5) and QGIS 4 (Qt6).

Usage (from plugin root):
  python compile_resources.py
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys

PLUGIN_ROOT = os.path.dirname(os.path.abspath(__file__))
QRC = os.path.join(PLUGIN_ROOT, "resources", "resources.qrc")
OUT = os.path.join(PLUGIN_ROOT, "resources", "resources.py")


def find_pyrcc() -> str | None:
    for name in ("pyrcc6", "pyrcc5"):
        path = shutil.which(name)
        if path:
            return path
    return None


def main() -> int:
    pyrcc = find_pyrcc()
    if not pyrcc:
        print(
            "error: pyrcc6 or pyrcc5 not found on PATH. "
            "Use the QGIS OSGeo4W shell or add QGIS bin to PATH.",
            file=sys.stderr,
        )
        return 1
    if not os.path.isfile(QRC):
        print(f"error: missing {QRC}", file=sys.stderr)
        return 1

    print(f"Using {pyrcc}")
    subprocess.check_call([pyrcc, "-o", OUT, QRC])

    with open(OUT, encoding="utf-8") as f:
        text = f.read()

    text = re.sub(
        r"from PyQt[56](\.QtCore)? import QtCore",
        "from qgis.PyQt import QtCore",
        text,
        count=1,
    )
    if "from qgis.PyQt import QtCore" not in text:
        raise RuntimeError(
            "resources.py still uses PyQt5/PyQt6 — patch failed. "
            "Edit resources/resources.py: use 'from qgis.PyQt import QtCore'."
        )

    header = (
        "# -*- coding: utf-8 -*-\n"
        "# Regenerated by compile_resources.py — use qgis.PyQt for QGIS 3/4.\n\n"
    )
    if not text.lstrip().startswith("# -*- coding"):
        text = header + text.lstrip()
    else:
        lines = text.splitlines(True)
        if len(lines) > 1 and "qgis.PyQt" not in lines[0] and "qgis.PyQt" not in lines[1]:
            lines.insert(1, "# Regenerated by compile_resources.py — use qgis.PyQt for QGIS 3/4.\n")
            text = "".join(lines)

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)

    print(f"Wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
