# -*- coding: utf-8 -*-
"""
/***************************************************************************
 VecPlugin
                                 A QGIS plugin
 Integration with VEC inference service for building detection
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-12-09
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Anthony_FieldWatch
        email                : kadibiaenu@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, QThread, pyqtSignal
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.core import (
    QgsVectorLayer, QgsProject, QgsMessageLog, 
    Qgis
)

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .vec_plugin_dialog import VecPluginDialog
from .vec_inference_client import VecInferenceClient
import os.path
import json
import tempfile


class InferenceWorker(QThread):
    """Worker thread for running inference asynchronously."""
    
    finished = pyqtSignal(str)  # Shapefile path
    error = pyqtSignal(str)
    progress = pyqtSignal(int, str)
    
    def __init__(self, client, raster_layer, crop_geometry=None):
        QThread.__init__(self)
        self.client = client
        self.raster_layer = raster_layer
        self.crop_geometry = crop_geometry
    
    def run(self):
        try:
            QgsMessageLog.logMessage(
                "InferenceWorker.run() started",
                "VEC Plugin",
                Qgis.Info
            )
            
            def progress_callback(value, message):
                self.progress.emit(value, message)
            
            QgsMessageLog.logMessage(
                f"Calling process_raster_layer with layer: {self.raster_layer.name()}",
                "VEC Plugin",
                Qgis.Info
            )
            
            shapefile_path = self.client.process_raster_layer(
                self.raster_layer,
                progress_callback,
                self.crop_geometry
            )
            
            QgsMessageLog.logMessage(
                f"Process completed successfully, shapefile: {shapefile_path}",
                "VEC Plugin",
                Qgis.Info
            )
            
            self.finished.emit(shapefile_path)
        except Exception as e:
            import traceback
            error_msg = f"InferenceWorker error: {str(e)}\n{traceback.format_exc()}"
            QgsMessageLog.logMessage(
                error_msg,
                "VEC Plugin",
                Qgis.Critical
            )
            self.error.emit(str(e))


class VecPlugin:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'VecPlugin_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&vec_plugin')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('VecPlugin', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/vec_plugin/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Vec Inference'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&vec_plugin'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = VecPluginDialog(iface=self.iface)

        # Populate layers in case new layers were added
        self.dlg.populate_layers()
        
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        
        QgsMessageLog.logMessage(
            f"Dialog closed with result: {result} (1=Accepted/OK, 0=Rejected/Cancel)",
            "VEC Plugin",
            Qgis.Info
        )
        
        QgsMessageLog.logMessage(
            f"Dialog result: {result}",
            "VEC Plugin",
            Qgis.Info
        )
        
        # See if OK was pressed
        if result:
            try:
                QgsMessageLog.logMessage(
                    "OK button clicked, starting processing...",
                    "VEC Plugin",
                    Qgis.Info
                )
                
                # Get values from dialog
                input_layer = self.dlg.get_input_layer()
                output_name = self.dlg.get_output_layer_name()
                crop_geometry = self.dlg.get_crop_geometry()
                
                QgsMessageLog.logMessage(
                    f"Retrieved values - input_layer: {input_layer}, output_name: {output_name}, crop_geometry: {crop_geometry is not None}",
                    "VEC Plugin",
                    Qgis.Info
                )
                
                if not input_layer:
                    QgsMessageLog.logMessage(
                        "No input layer selected",
                        "VEC Plugin",
                        Qgis.Warning
                    )
                    self.iface.messageBar().pushMessage(
                        "Error", 
                        "Please select an input raster layer.",
                        level=1,  # Warning level
                        duration=3
                    )
                    return
                
                # Validate polygon is drawn (mandatory)
                if not crop_geometry or crop_geometry.isEmpty():
                    QgsMessageLog.logMessage(
                        "No polygon drawn - polygon is required",
                        "VEC Plugin",
                        Qgis.Warning
                    )
                    self.iface.messageBar().pushMessage(
                        "Error",
                        "Please draw a polygon on the map before processing.",
                        level=1,
                        duration=5
                    )
                    return
                
                # Hardcoded service URLs
                INFERENCE_SERVICE_URL = "https://inference-service-proxy-127864475088.us-central1.run.app"
                UPLOAD_SERVICE_URL = "https://upload-service-127864475088.us-central1.run.app"
                
                QgsMessageLog.logMessage(
                    f"Initializing inference client with URLs: inference={INFERENCE_SERVICE_URL}, upload={UPLOAD_SERVICE_URL}",
                    "VEC Plugin",
                    Qgis.Info
                )
                
                # Initialize inference client with hardcoded URLs
                try:
                    client = VecInferenceClient(INFERENCE_SERVICE_URL, upload_url=UPLOAD_SERVICE_URL)
                    QgsMessageLog.logMessage(
                        "Inference client initialized successfully",
                        "VEC Plugin",
                        Qgis.Info
                    )
                except Exception as e:
                    QgsMessageLog.logMessage(
                        f"Failed to initialize inference client: {str(e)}",
                        "VEC Plugin",
                        Qgis.Critical
                    )
                    import traceback
                    QgsMessageLog.logMessage(
                        f"Traceback: {traceback.format_exc()}",
                        "VEC Plugin",
                        Qgis.Critical
                    )
                    self.iface.messageBar().pushMessage(
                        "Error",
                        f"Failed to initialize inference client: {str(e)}",
                        level=2,
                        duration=5
                    )
                    return
                
                # Show progress bar
                self.dlg.progressBar.setVisible(True)
                self.dlg.progressBar.setValue(0)
                self.dlg.statusLabel.setText("Processing...")
                
                QgsMessageLog.logMessage(
                    "Creating worker thread...",
                    "VEC Plugin",
                    Qgis.Info
                )
                
                # Create worker thread
                self.worker = InferenceWorker(client, input_layer, crop_geometry)
                self.worker.progress.connect(self._on_progress)
                self.worker.finished.connect(lambda shapefile_path: self._on_finished(shapefile_path, output_name, input_layer))
                self.worker.error.connect(self._on_error)
                
                QgsMessageLog.logMessage(
                    "Starting worker thread...",
                    "VEC Plugin",
                    Qgis.Info
                )
                
                self.worker.start()
                
                QgsMessageLog.logMessage(
                    "Worker thread started",
                    "VEC Plugin",
                    Qgis.Info
                )
                
            except Exception as e:
                QgsMessageLog.logMessage(
                    f"Unexpected error in run() method: {str(e)}",
                    "VEC Plugin",
                    Qgis.Critical
                )
                import traceback
                QgsMessageLog.logMessage(
                    f"Traceback: {traceback.format_exc()}",
                    "VEC Plugin",
                    Qgis.Critical
                )
                self.iface.messageBar().pushMessage(
                    "Error",
                    f"Unexpected error: {str(e)}",
                    level=2,
                    duration=5
                )
    
    def _on_progress(self, value, message):
        """Update progress bar."""
        self.dlg.progressBar.setValue(value)
        self.dlg.statusLabel.setText(message)
    
    def _on_finished(self, shapefile_path, output_name, input_layer):
        """Handle successful inference completion."""
        try:
            # Create vector layer from shapefile
            vector_layer = self._create_vector_layer(shapefile_path, output_name, input_layer.crs())
            
            # Add layer to QGIS
            QgsProject.instance().addMapLayer(vector_layer)
            
            # Zoom to layer
            self.iface.mapCanvas().setExtent(vector_layer.extent())
            self.iface.mapCanvas().refresh()
            
            # Count features
            feature_count = vector_layer.featureCount()
            
            self.iface.messageBar().pushMessage(
                "Success", 
                f"Created layer '{output_name}' with {feature_count} building(s) detected.",
                level=0,
                duration=5
            )
            
            self.dlg.progressBar.setVisible(False)
            self.dlg.statusLabel.setText("Complete!")
            
        except Exception as e:
            self._on_error(str(e))
    
    def _on_error(self, error_message):
        """Handle inference errors."""
        self.dlg.progressBar.setVisible(False)
        self.dlg.statusLabel.setText("Error occurred")
        self.iface.messageBar().pushMessage(
            "Error",
            f"Inference failed: {error_message}",
            level=2,  # Critical
            duration=5
        )
        QgsMessageLog.logMessage(
            f"Inference error: {error_message}",
            "VEC Plugin",
            Qgis.Critical
        )
    
    def _create_vector_layer(self, shapefile_path, layer_name, crs):
        """
        Create a QGIS vector layer from shapefile path.
        
        :param shapefile_path: Path to shapefile (.shp file)
        :type shapefile_path: str
        :param layer_name: Name for the new layer
        :type layer_name: str
        :param crs: Coordinate reference system
        :type crs: QgsCoordinateReferenceSystem
        :returns: QGIS vector layer
        :rtype: QgsVectorLayer
        """
        # Create vector layer directly from shapefile
        vector_layer = QgsVectorLayer(
            shapefile_path,
            layer_name,
            "ogr"
        )
        
        if not vector_layer.isValid():
            raise Exception(f"Failed to create vector layer from shapefile: {shapefile_path}")
        
        # Set CRS
        vector_layer.setCrs(crs)
        
        return vector_layer
