# -*- coding: utf-8 -*-
"""
/***************************************************************************
 VecPlugin
                                 A QGIS plugin
 Integration with VEC inference service for building detection
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-12-09
        git sha              : $Format:%H$
        copyright            : (C) 2025 FieldWatch AI
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, QThread, pyqtSignal, QTimer
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QDialog
from qgis.core import (
    QgsVectorLayer, QgsProject, QgsMessageLog,
    QgsDistanceArea, Qgis
)

# Initialize Qt resources (resources/resources.py via resources package)
from .resources import *
from .dialogs.vec_plugin_dialog import VecPluginDialog
from .dialogs.order_imagery_dialog import OrderImageryDialog
from .dialogs.one_click_settings_dialog import OneClickSettingsDialog
from .dialogs.obstacle_removal_dialog import ObstacleRemovalDialog
from .core.one_click_controller import OneClickSegmentationController
from .core.vec_inference_client import VecInferenceClient
from .core.api_config import INFERENCE_BASE_URL, UPLOAD_BASE_URL
from .core.qt_compat import dialog_exec
from .core import trial_helpers
import os.path
import tempfile
import uuid


class InferenceWorker(QThread):
    """Worker thread for running inference asynchronously."""
    
    finished = pyqtSignal(object)  # Result payload
    error = pyqtSignal(str)
    progress = pyqtSignal(int, str)
    
    def __init__(self, client, raster_layer, crop_geometry=None, crop_geometry_crs=None, detection_type="building"):
        QThread.__init__(self)
        self.client = client
        self.raster_layer = raster_layer
        self.crop_geometry = crop_geometry
        self.crop_geometry_crs = crop_geometry_crs
        self.detection_type = detection_type
    
    def run(self):
        try:
            def progress_callback(value, message):
                self.progress.emit(value, message)
            
            result_payload = self.client.process_raster_layer(
                self.raster_layer,
                progress_callback,
                self.crop_geometry,
                crop_geometry_crs=self.crop_geometry_crs,
                detection_type=self.detection_type
            )
            
            self.finished.emit(result_payload)
        except Exception as e:
            self.error.emit(f"{type(e).__name__}: {str(e)}")


class VecPlugin:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'VecPlugin_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&FieldWatch Vectorizer')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None
        self.one_click_dlg = None
        self.one_click_controller = None
        self.obstacle_removal_dlg = None
        self._segmentation_predictor = None
        self._segmentation_preload_worker = None
        self._segmentation_preloading = False

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('VecPlugin', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/vec_plugin/icons/binocular.png'
        self.add_action(
            icon_path,
            text=self.tr(u'FieldWatch'),
            callback=self.run,
            parent=self.iface.mainWindow())

        self.add_action(
            icon_path,
            text=self.tr(u'Order drone imagery'),
            callback=self.run_order_imagery,
            add_to_toolbar=False,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        if self.one_click_controller:
            self.one_click_controller.shutdown()
        if self.obstacle_removal_dlg is not None:
            try:
                self.obstacle_removal_dlg.shutdown()
                self.obstacle_removal_dlg.hide()
            except RuntimeError:
                pass
            self.obstacle_removal_dlg = None
        self.one_click_dlg = None
        self.one_click_controller = None
        if self._segmentation_predictor is not None:
            try:
                self._segmentation_predictor.cleanup()
            except Exception:
                pass
            self._segmentation_predictor = None
        self._segmentation_preload_worker = None
        self._segmentation_preloading = False
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&FieldWatch Vectorizer'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = VecPluginDialog(iface=self.iface)
            try:
                self.dlg.one_click_requested.disconnect()
            except Exception:
                pass
            self.dlg.one_click_requested.connect(self.run_one_click_segmentation)
            try:
                self.dlg.obstacle_removal_requested.disconnect()
            except Exception:
                pass
            self.dlg.obstacle_removal_requested.connect(self.run_obstacle_removal)

        QTimer.singleShot(0, self._preload_segmentation_model)

        # Populate layers in case new layers were added
        self.dlg.populate_layers()

        # Reset processing flag
        self._is_processing = False
        
        # Connect to processing_started signal (disconnect first to avoid duplicates)
        try:
            self.dlg.processing_started.disconnect()
        except:
            pass
        self.dlg.processing_started.connect(self._start_processing)

        # show the dialog (non-modal so it stays open during processing)
        self.dlg.show()
        # Run the dialog event loop
        dialog_exec(self.dlg)

    def run_order_imagery(self):
        """Open the Order drone imagery dialog."""
        if not hasattr(self, 'order_imagery_dlg') or self.order_imagery_dlg is None:
            self.order_imagery_dlg = OrderImageryDialog(iface=self.iface)
        self.order_imagery_dlg.show()
        self.order_imagery_dlg.raise_()
        self.order_imagery_dlg.activateWindow()

    def _preload_segmentation_model(self):
        """Load segmentation model when the main plugin opens (background)."""
        if self._segmentation_predictor is not None:
            return
        if self._segmentation_preloading:
            return
        try:
            from .core.model_venv import deps_installed
            from .core.model_config import checkpoint_exists, resolve_checkpoint_path
            from .core.model_predictor import build_model_predictor_config
            from .core.one_click_workers import ModelInitWorker
        except Exception:
            return

        if not deps_installed() or not checkpoint_exists():
            return

        try:
            config = build_model_predictor_config(resolve_checkpoint_path())
        except Exception:
            return

        self._segmentation_preloading = True
        self._segmentation_preload_worker = ModelInitWorker(config)
        self._segmentation_preload_worker.finished.connect(
            self._on_segmentation_preload_finished
        )
        self._segmentation_preload_worker.error.connect(self._on_segmentation_preload_error)
        self._segmentation_preload_worker.start()
        self.iface.messageBar().pushMessage(
            "FieldWatch",
            self.tr("First startup can take about a minute (background)…"),
            level=Qgis.MessageLevel.Info,
            duration=5,
        )

    def _on_segmentation_preload_finished(self, predictor, _msg: str):
        self._segmentation_preloading = False
        self._segmentation_predictor = predictor
        if self.one_click_controller is not None:
            self.one_click_controller.apply_shared_predictor(predictor)
            self.one_click_controller.refresh_status()
        QgsMessageLog.logMessage(
            "Segmentation ready (background startup complete).",
            "FieldWatch One-Click",
            Qgis.MessageLevel.Info,
        )

    def _on_segmentation_preload_error(self, message: str):
        self._segmentation_preloading = False
        QgsMessageLog.logMessage(
            f"Segmentation preload failed: {message}",
            "FieldWatch One-Click",
            Qgis.MessageLevel.Warning,
        )

    def run_one_click_segmentation(self):
        """Open the one-click segmentation settings window."""
        if self.one_click_dlg is None:
            self.one_click_dlg = OneClickSettingsDialog(
                self.iface, pack_dialog=self.dlg
            )
            self.one_click_controller = OneClickSegmentationController(
                self.iface, self.one_click_dlg, plugin=self
            )
            self.one_click_dlg.set_controller(self.one_click_controller)
            self.one_click_controller.apply_shared_predictor(self._segmentation_predictor)
        else:
            self.one_click_controller.apply_shared_predictor(self._segmentation_predictor)
            self.one_click_dlg.refresh_ui_local()
        if self._segmentation_predictor is None and not self._segmentation_preloading:
            QTimer.singleShot(0, self._preload_segmentation_model)
        self.one_click_dlg.show()
        self.one_click_dlg.raise_()
        self.one_click_dlg.activateWindow()

    def run_obstacle_removal(self):
        """Open AI Obstacle Removal (nano banana / POST /qgis/edit)."""
        if self.obstacle_removal_dlg is None:
            self.obstacle_removal_dlg = ObstacleRemovalDialog(
                self.iface, pack_dialog=self.dlg
            )
        else:
            self.obstacle_removal_dlg.licensePanel.refresh_trial_state(force=True)
            self.obstacle_removal_dlg.populate_layers()
            self.obstacle_removal_dlg._sync_apply_state()
        self.obstacle_removal_dlg.show()
        self.obstacle_removal_dlg.raise_()
        self.obstacle_removal_dlg.activateWindow()
    
    def _start_processing(self):
        """Start the inference processing."""
        # Prevent multiple simultaneous processing
        if hasattr(self, '_is_processing') and self._is_processing:
            return
        
        try:
            self._is_processing = True
            
            # Disconnect signal to prevent restart
            try:
                self.dlg.processing_started.disconnect()
            except:
                pass
            
            # Get values from dialog
            input_layer = self.dlg.get_input_layer()
            output_name = self.dlg.get_output_layer_name()
            crop_geometry = self.dlg.get_crop_geometry()
            jwt_token = self.dlg.get_jwt_token()
            license_key = self.dlg.get_license_key()
            detection_type = self.dlg.get_detection_type()

            if not input_layer:
                self.iface.messageBar().pushMessage(
                    "Error",
                    "Please select an input raster layer.",
                    level=1,
                    duration=3,
                )
                self._is_processing = False
                return

            if not crop_geometry or crop_geometry.isEmpty():
                self.iface.messageBar().pushMessage(
                    "Error",
                    "Please draw a polygon on the map before processing.",
                    level=1,
                    duration=5,
                )
                self._is_processing = False
                return

            crs = (
                self.iface.mapCanvas().mapSettings().destinationCrs()
                if self.iface and self.iface.mapCanvas()
                else QgsProject.instance().crs()
            )
            if not crs.isValid():
                crs = QgsProject.instance().crs()
            da = QgsDistanceArea()
            da.setSourceCrs(crs, QgsProject.instance().transformContext())
            da.setEllipsoid(crs.ellipsoidAcronym())
            area_m2 = da.measureArea(crop_geometry)
            area_ha = area_m2 / 10000.0
            if area_ha > 5.5:
                self.iface.messageBar().pushMessage(
                    "Error",
                    "Crop area is {:.2f} ha. Maximum allowed for inference is 5.5 ha. Please draw a smaller area.".format(
                        area_ha
                    ),
                    level=1,
                    duration=8,
                )
                self._is_processing = False
                return

            trial_receipt = None
            trial_install_key = None
            trial_server_id = None

            if jwt_token:
                client = VecInferenceClient(
                    INFERENCE_BASE_URL,
                    upload_url=UPLOAD_BASE_URL,
                    jwt_token=jwt_token,
                    license_key=license_key,
                )
            else:
                from .core.trial_access import shared as trial_shared

                acc = trial_shared()
                acc.sync_pending_usages()
                if not self.dlg.get_trial_billable_idempotency_key():
                    acc.get_billable_idempotency_key()

                ok, msg, usage, trial_receipt = acc.consume_for_large_area_infer()
                if not ok:
                    if usage:
                        self.dlg.apply_trial_usage_denied(usage)
                    self.iface.messageBar().pushMessage(
                        "Error",
                        (msg or "Trial usage failed.")[:300],
                        level=1,
                        duration=10,
                    )
                    self._is_processing = False
                    return

                self.dlg.clear_trial_billable_idempotency_key()
                self.dlg.apply_trial_usage_response(usage or {})

                trial_install_key = acc.install_key
                trial_server_id = acc.trial_id

                client = VecInferenceClient(
                    INFERENCE_BASE_URL,
                    upload_url=UPLOAD_BASE_URL,
                    jwt_token=None,
                    license_key=None,
                    trial_receipt=trial_receipt,
                    trial_install_key=trial_install_key,
                    trial_server_id=trial_server_id,
                )

            # Disable Run/Cancel during processing
            self.dlg.runButton.setEnabled(False)
            self.dlg.cancelButton.setEnabled(False)
            
            # Show progress bar
            self.dlg.progressBar.setVisible(True)
            self.dlg.progressBar.setValue(0)
            self.dlg.statusLabel.setText("Processing...")
            
            # Store output_name and input_layer for use in callbacks
            self._processing_output_name = output_name
            self._processing_input_layer = input_layer
            
            # Get canvas CRS for crop geometry (polygon was drawn on canvas)
            canvas_crs = None
            if self.iface and self.iface.mapCanvas():
                project = QgsProject.instance()
                canvas_crs = project.crs() if project else None
            
            # Create worker thread
            self.worker = InferenceWorker(
                client,
                input_layer,
                crop_geometry,
                crop_geometry_crs=canvas_crs,
                detection_type=detection_type
            )
            self.worker.progress.connect(self._on_progress)
            self.worker.finished.connect(self._on_finished)
            self.worker.error.connect(self._on_error)
            
            self.worker.start()
            
        except Exception as e:
            # Clean up any partially created worker
            if hasattr(self, 'worker') and self.worker:
                try:
                    self.worker.progress.disconnect()
                    self.worker.finished.disconnect()
                    self.worker.error.disconnect()
                except:
                    pass
                self.worker = None
            
            self._is_processing = False
            
            # Re-enable buttons
            self.dlg._sync_ok_button_state()
            self.dlg.cancelButton.setEnabled(True)
            
            # Reconnect processing signal
            try:
                self.dlg.processing_started.disconnect()
            except:
                pass
            self.dlg.processing_started.connect(self._start_processing)
            
            self.iface.messageBar().pushMessage(
                "Error",
                f"Unexpected error occurred: {str(e)[:200]}",
                level=2,
                duration=10
            )
    
    def _on_progress(self, value, message):
        """Update progress bar."""
        self.dlg.progressBar.setValue(value)
        self.dlg.statusLabel.setText(message)
    
    def _on_finished(self, result_payload):
        """Handle successful inference completion."""
        try:
            output_name = self._processing_output_name
            input_layer = self._processing_input_layer

            # Backward compatibility: older client returns shapefile path string.
            if isinstance(result_payload, dict):
                shapefile_path = result_payload.get("shapefile_path")
                summary_csv_path = result_payload.get("summary_csv_path")
            else:
                shapefile_path = result_payload
                summary_csv_path = None
            if not shapefile_path:
                raise Exception("Inference did not return a shapefile path.")
            
            # Create vector layer from shapefile
            vector_layer = self._create_vector_layer(shapefile_path, output_name, input_layer.crs())
            
            # Add layer to QGIS
            QgsProject.instance().addMapLayer(vector_layer)

            # Optional panel summary table for /roofnel responses
            if summary_csv_path:
                summary_layer_name = f"{output_name}_panels_summary"
                csv_layer = self._create_csv_table_layer(summary_csv_path, summary_layer_name)
                if csv_layer and csv_layer.isValid():
                    QgsProject.instance().addMapLayer(csv_layer)
            
            # Zoom to layer
            self.iface.mapCanvas().setExtent(vector_layer.extent())
            self.iface.mapCanvas().refresh()
            
            # Count features
            feature_count = vector_layer.featureCount()
            
            self.iface.messageBar().pushMessage(
                "Success", 
                f"Created layer '{output_name}' with {feature_count} feature(s).",
                level=0,
                duration=5
            )

            QTimer.singleShot(0, self.dlg.refresh_trial_state)
            
            self.dlg.progressBar.setVisible(False)
            self.dlg.statusLabel.setText("Complete!")
            
            # Re-enable buttons
            self.dlg._sync_ok_button_state()
            self.dlg.cancelButton.setEnabled(True)
            
            # Reset processing flag
            self._is_processing = False
            
            # Close dialog after a short delay (use done() to avoid triggering accept() signal)
            QTimer.singleShot(1000, lambda: self.dlg.done(QDialog.Accepted))
            
        except Exception as e:
            # Ensure cleanup happens
            if hasattr(self, 'worker') and self.worker:
                try:
                    self.worker.progress.disconnect()
                    self.worker.finished.disconnect()
                    self.worker.error.disconnect()
                except:
                    pass
            self._is_processing = False
            self._on_error(str(e))
    
    def _on_error(self, error_message):
        """Handle inference errors."""
        try:
            # Clean up worker thread
            if hasattr(self, 'worker') and self.worker:
                try:
                    # Disconnect all signals first
                    self.worker.progress.disconnect()
                    self.worker.finished.disconnect()
                    self.worker.error.disconnect()
                except:
                    pass
                
                # Wait for thread to finish (with timeout)
                if self.worker.isRunning():
                    self.worker.wait(1000)  # Wait up to 1 second
                    if self.worker.isRunning():
                        # Force terminate if still running
                        self.worker.terminate()
                        self.worker.wait(500)
                
                # Clean up reference
                self.worker = None
            
            # Reset processing flag
            self._is_processing = False
            
            # Reset UI
            self.dlg.progressBar.setVisible(False)
            self.dlg.statusLabel.setText(f"Error: {error_message[:100]}")
            
            # Show error message
            self.iface.messageBar().pushMessage(
                "Error",
                f"Inference failed: {error_message[:200]}",
                level=2,  # Critical
                duration=10
            )
            self.dlg._sync_ok_button_state()
            self.dlg.cancelButton.setEnabled(True)
            
            # Reconnect processing signal to allow retry
            try:
                self.dlg.processing_started.disconnect()
            except:
                pass
            self.dlg.processing_started.connect(self._start_processing)
            
        except Exception as e:
            # Last resort cleanup
            self._is_processing = False
            # Sanitize URLs from error messages
            error_msg = str(e)
            import re
            url_pattern = r'https?://[^\s<>"{}|\\^`\[\]]+'
            sanitized_error = re.sub(url_pattern, '[REDACTED]', error_msg)
            QgsMessageLog.logMessage(
                f"Error in error handler: {sanitized_error}",
                "VEC Plugin",
                Qgis.Critical
            )
    
    def _create_vector_layer(self, shapefile_path, layer_name, crs):
        """
        Create a QGIS vector layer from shapefile path.
        
        :param shapefile_path: Path to shapefile (.shp file)
        :type shapefile_path: str
        :param layer_name: Name for the new layer
        :type layer_name: str
        :param crs: Coordinate reference system
        :type crs: QgsCoordinateReferenceSystem
        :returns: QGIS vector layer
        :rtype: QgsVectorLayer
        """
        # Create vector layer directly from shapefile
        vector_layer = QgsVectorLayer(
            shapefile_path,
            layer_name,
            "ogr"
        )
        
        if not vector_layer.isValid():
            raise Exception(f"Failed to create vector layer from shapefile: {shapefile_path}")
        
        # Set CRS
        vector_layer.setCrs(crs)
        
        return vector_layer

    def _create_csv_table_layer(self, csv_path, layer_name):
        """
        Create a non-spatial QGIS table layer from CSV path.

        :param csv_path: Path to CSV file
        :type csv_path: str
        :param layer_name: Name for the table layer
        :type layer_name: str
        :returns: QGIS vector layer table
        :rtype: QgsVectorLayer
        """
        # Prefer delimited text provider as a plain attribute table.
        csv_uri = "file:///{}?type=csv&detectTypes=yes&geomType=none".format(
            csv_path.replace("\\", "/")
        )
        table_layer = QgsVectorLayer(csv_uri, layer_name, "delimitedtext")
        if table_layer.isValid():
            return table_layer

        # Fallback to OGR CSV driver.
        table_layer = QgsVectorLayer(csv_path, layer_name, "ogr")
        if not table_layer.isValid():
            raise Exception(f"Failed to create summary CSV table layer from: {csv_path}")
        return table_layer
