# -*- coding: utf-8 -*-
"""
/***************************************************************************
 VecPluginDialog
                                 A QGIS plugin
 Integration with VEC inference service for building detection
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-12-09
        git sha              : $Format:%H$
        copyright            : (C) 2025 FieldWatch AI
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

import uuid

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets, QtCore, QtGui
from qgis.PyQt.QtCore import QUrl
from qgis.PyQt.QtGui import QDesktopServices
from qgis.core import QgsProject, QgsGeometry, QgsWkbTypes, QgsPointXY, QgsMessageLog, Qgis
from qgis.gui import QgsMapToolCapture, QgsRubberBand
from .order_imagery_dialog import OrderImageryDialog
from .feedback_dialog import FeedbackDialog
from .api_config import INFERENCE_BASE_URL

# Browser destination for paid licence keys.
FIELDWATCH_HOME_URL = "https://usefieldwatch.com/"
from . import trial_helpers

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'vec_plugin_dialog_base.ui'))


class PolygonCaptureTool(QgsMapToolCapture):
    """Custom map tool for capturing polygon geometry."""
    
    finished = QtCore.pyqtSignal(QgsGeometry)
    
    def __init__(self, canvas, cad_dock_widget=None):
        super(PolygonCaptureTool, self).__init__(canvas, cad_dock_widget, QgsMapToolCapture.CapturePolygon)
        self.canvas = canvas
        self.points = []
        self.rubber_band = None
    
    def canvasReleaseEvent(self, event):
        """Handle mouse release events."""
        if event.button() == QtCore.Qt.RightButton:
            # Right click finishes the polygon
            if len(self.points) >= 3:
                # Create polygon from points
                polygon_points = self.points + [self.points[0]]  # Close polygon
                geometry = QgsGeometry.fromPolygonXY([polygon_points])
                self.finished.emit(geometry)
            else:
                # Not enough points
                self.finished.emit(QgsGeometry())
            self._cleanup_rubber_band()
            self.points = []
        elif event.button() == QtCore.Qt.LeftButton:
            # Left click adds a point
            point = self.toMapCoordinates(event.pos())
            self.points.append(QgsPointXY(point))
            # Draw temporary rubber band
            if self.rubber_band is None:
                self.rubber_band = QgsRubberBand(self.canvas, QgsWkbTypes.PolygonGeometry)
                self.rubber_band.setColor(QtCore.Qt.red)
                self.rubber_band.setWidth(2)
                # Match order imagery dialog styling: semi-transparent red fill
                self.rubber_band.setFillColor(QtGui.QColor(255, 0, 0, 60))
            if len(self.points) > 1:
                self.rubber_band.reset(QgsWkbTypes.PolygonGeometry)
                for p in self.points:
                    self.rubber_band.addPoint(p, False)
                self.rubber_band.addPoint(self.points[0], True)  # Close polygon
                self.rubber_band.show()
    
    def _cleanup_rubber_band(self):
        """Clean up rubber band."""
        if self.rubber_band:
            self.rubber_band.reset()
            self.rubber_band = None
    
    def deactivate(self):
        """Clean up when tool is deactivated."""
        self._cleanup_rubber_band()
        self.points = []
        super(PolygonCaptureTool, self).deactivate()


class VecPluginDialog(QtWidgets.QDialog, FORM_CLASS):
    # Signal emitted when polygon is drawn
    polygon_drawn = QtCore.pyqtSignal(QgsGeometry)
    # Signal emitted when Run is clicked (but dialog stays open)
    processing_started = QtCore.pyqtSignal()
    
    def __init__(self, parent=None, iface=None):
        """Constructor."""
        super(VecPluginDialog, self).__init__(parent)
        self.iface = iface
        self.crop_geometry = None
        self.map_tool = None
        self.previous_map_tool = None
        self.order_imagery_dialog = None
        
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        
        # Initialize license-related variables
        self.license_key = None
        self.jwt_token = None
        self.token_expiry = None

        # Trial (GET /qgis/trial/state + usage before runs; no JWT)
        self._install_key = trial_helpers.ensure_install_key()
        self._trial_id = trial_helpers.get_stored_trial_id() or None
        self.trial_uses_total = None
        self.trial_uses_remaining = None
        self.trial_status = None  # API trial_state: active | exhausted | revoked
        # One idempotency_key per trial billable attempt (OK click); reused on network retry until POST completes.
        self._trial_billable_idempotency_key = None

        self.trialQuotaLabel = QtWidgets.QLabel("")
        self.trialQuotaLabel.setWordWrap(True)
        self.licenseFormLayout.addRow(
            QtWidgets.QLabel(self.tr("Trial quota:")),
            self.trialQuotaLabel,
        )
        
        # Populate the input layer combo box with raster layers
        self.populate_layers()
        
        # Set default output layer name
        self.outputLayerLineEdit.setText("Building_Detections")
        if hasattr(self, "detectionTypeCombo"):
            self.detectionTypeCombo.setCurrentText("Building")
        
        # Hide progress bar initially
        self.progressBar.setVisible(False)
        
        # Connect polygon drawing buttons
        self.drawPolygonButton.clicked.connect(self.start_polygon_drawing)
        self.clearPolygonButton.clicked.connect(self.clear_polygon)
        
        # Connect license validation button
        self.validateLicenseButton.clicked.connect(self.validate_license)
        
        # One morphing button: Generate Trial Key (refresh/bootstrap) until trial is exhausted,
        # then Get Licence (opens FieldWatch). Paid JWT always shows Get Licence.
        self.getLicenseKeyButton.clicked.connect(self._on_license_action_clicked)
        self._update_license_action_button()

        if hasattr(self, "howToUsePluginButton"):
            self.howToUsePluginButton.clicked.connect(self.open_how_to_use_plugin_video)

        if hasattr(self, "sendFeedbackButton"):
            self.sendFeedbackButton.clicked.connect(self.open_feedback_dialog)

        # Connect Order drone imagery button
        if hasattr(self, "orderImageryButton"):
            self.orderImageryButton.clicked.connect(self.open_order_imagery_dialog)
        
        # Connect signal
        self.polygon_drawn.connect(self.on_polygon_drawn)

        self.refreshButton.clicked.connect(self._refresh_plugin_state)

        # Disable Run until polygon is drawn AND (paid JWT or active trial)
        self.runButton.setEnabled(False)
        self.runButton.setDefault(True)

        # Non-blocking trial state fetch after UI is ready
        QtCore.QTimer.singleShot(0, self.refresh_trial_state)
    
    def populate_layers(self):
        """Populate the input layer combo box with available raster layers."""
        self.inputLayerCombo.clear()
        
        # Get all layers from the project
        layers = QgsProject.instance().mapLayers().values()
        
        # Filter for raster layers
        raster_layers = [layer for layer in layers if layer.type() == 1]  # 1 = raster layer
        
        if raster_layers:
            for layer in raster_layers:
                self.inputLayerCombo.addItem(layer.name(), layer)
            # Explicitly enable the combo box when layers are found
            self.inputLayerCombo.setEnabled(True)
        else:
            self.inputLayerCombo.addItem("No raster layers available", None)
            self.inputLayerCombo.setEnabled(False)
    
    def get_input_layer(self):
        """Get the selected input raster layer."""
        if self.inputLayerCombo.currentData():
            return self.inputLayerCombo.currentData()
        return None
    
    def get_output_layer_name(self):
        """Get the output layer name."""
        name = self.outputLayerLineEdit.text().strip()
        if not name:
            return "Building_Detections"
        return name
    
    def get_crop_geometry(self):
        """Get the crop polygon geometry."""
        return self.crop_geometry

    def get_detection_type(self):
        """Get selected detection type."""
        if hasattr(self, "detectionTypeCombo"):
            text = self.detectionTypeCombo.currentText().strip().lower()
            return "solar_panel" if text == "solar panel" else "building"
        return "building"
    
    def get_license_key(self):
        """Get the license key."""
        return self.license_key
    
    def get_jwt_token(self):
        """Get the JWT token."""
        return self.jwt_token

    def get_install_key(self):
        return self._install_key

    def get_trial_id(self):
        return self._trial_id

    def trial_can_run(self):
        """True if trial mode can start a billable run (paid JWT takes precedence elsewhere)."""
        if self.jwt_token:
            return False
        return (
            self.trial_status == "active"
            and self.trial_uses_remaining is not None
            and self.trial_uses_remaining > 0
        )

    def _license_action_is_generate_trial(self):
        """True when the single licence button should refresh/bootstrap trial (not open the shop)."""
        if self.jwt_token:
            return False
        if self.trial_status == "exhausted":
            return False
        if self.trial_status == "revoked":
            return False
        rem = self.trial_uses_remaining
        if rem is not None and rem <= 0:
            return False
        return True

    def _update_license_action_button(self):
        """Morph label: Generate Trial Key while trial has runs; Get Licence once exhausted or paid."""
        if not hasattr(self, "getLicenseKeyButton"):
            return
        if self._license_action_is_generate_trial():
            self.getLicenseKeyButton.setText(self.tr("Generate Trial Key"))
            self.getLicenseKeyButton.setToolTip(
                self.tr(
                    "Contact the server to activate or refresh your free trial runs. "
                    "When your trial is used up, this becomes a link to get a paid licence."
                )
            )
        else:
            self.getLicenseKeyButton.setText(self.tr("Get Licence"))
            self.getLicenseKeyButton.setToolTip(
                self.tr("Open FieldWatch in your browser to get a paid licence key.")
            )

    def _on_license_action_clicked(self):
        if self._license_action_is_generate_trial():
            self.refresh_trial_state(show_error_dialog=True)
        else:
            self.open_fieldwatch_website()

    def _update_trial_quota_label(self):
        if self.jwt_token:
            self.trialQuotaLabel.setText(
                self.tr("Using paid license — runs use your key, not trial quota.")
            )
            self.trialQuotaLabel.setStyleSheet("color: gray;")
        elif self.trial_status is None and self.trial_uses_remaining is None:
            self.trialQuotaLabel.setText(self.tr("Loading trial status…"))
            self.trialQuotaLabel.setStyleSheet("color: blue;")
        else:
            total = self.trial_uses_total
            rem = self.trial_uses_remaining
            if total is not None and rem is not None:
                used = max(0, total - rem)
                txt = self.tr("{0} of {1} trial runs remaining (used {2}).").format(rem, total, used)
            elif rem is not None:
                txt = self.tr("{0} trial runs remaining.").format(rem)
            else:
                txt = self.tr("Trial status: {0}").format(self.trial_status or "unknown")
            if self.trial_status == "exhausted" or (rem is not None and rem <= 0):
                self.trialQuotaLabel.setStyleSheet("color: red;")
                txt += " " + self.tr("Register for a full license key at usefieldwatch.com.")
            elif self.trial_status == "revoked":
                self.trialQuotaLabel.setStyleSheet("color: red;")
            else:
                self.trialQuotaLabel.setStyleSheet("color: green;")
            self.trialQuotaLabel.setText(txt)
        self._update_license_action_button()

    def refresh_trial_state(self, show_error_dialog=False):
        """GET /qgis/trial/state — updates labels and persisted trial_id."""
        try:
            data = trial_helpers.fetch_trial_state(
                INFERENCE_BASE_URL,
                self._install_key,
                trial_id=self._trial_id,
                timeout=5,
            )
            tid = data.get("trial_id")
            if tid:
                self._trial_id = tid
                trial_helpers.set_stored_trial_id(tid)
            self.trial_uses_total = data.get("uses_total")
            self.trial_uses_remaining = data.get("uses_remaining")
            self.trial_status = data.get("trial_state")
            self._update_trial_quota_label()
            self._sync_ok_button_state()
        except Exception as e:
            self.trial_status = None
            self.trialQuotaLabel.setText(
                self.tr("Could not load trial status ({0}). You can still validate a paid license.").format(str(e)[:120])
            )
            self.trialQuotaLabel.setStyleSheet("color: orange;")
            QgsMessageLog.logMessage(
                f"Trial state refresh: {str(e)}",
                "VEC Plugin",
                Qgis.Warning,
            )
            if show_error_dialog:
                QtWidgets.QMessageBox.warning(
                    self,
                    self.tr("Trial status"),
                    str(e)[:500],
                )
            self._update_license_action_button()

    def apply_trial_usage_response(self, data):
        """Update UI after POST /qgis/trial/usage (allowed path)."""
        if data.get("uses_remaining") is not None:
            self.trial_uses_remaining = data["uses_remaining"]
            if self.trial_uses_remaining <= 0:
                self.trial_status = "exhausted"
        self._update_trial_quota_label()
        self._sync_ok_button_state()

    def _sync_ok_button_state(self):
        auth_ok = bool(self.jwt_token) or self.trial_can_run()
        self.runButton.setEnabled(
            bool(self.crop_geometry and not self.crop_geometry.isEmpty() and auth_ok)
        )

    def apply_trial_usage_denied(self, data):
        """Update UI after usage denied."""
        if data.get("uses_remaining") is not None:
            self.trial_uses_remaining = data["uses_remaining"]
        if data.get("trial_state"):
            self.trial_status = data["trial_state"]
        self._update_trial_quota_label()
        self._sync_ok_button_state()

    def get_trial_billable_idempotency_key(self):
        """Key for POST /qgis/trial/usage for the current OK click (max 128 chars)."""
        return self._trial_billable_idempotency_key

    def clear_trial_billable_idempotency_key(self):
        """Clear after POST /qgis/trial/usage completes (HTTP response received)."""
        self._trial_billable_idempotency_key = None

    def open_order_imagery_dialog(self):
        """Open the Order drone imagery dialog."""
        if not self.iface:
            QtWidgets.QMessageBox.warning(
                self,
                "Error",
                "Cannot open order dialog: QGIS interface not available."
            )
            return
        
        if self.order_imagery_dialog is None:
            self.order_imagery_dialog = OrderImageryDialog(iface=self.iface, parent=self)
        
        self.order_imagery_dialog.show()
        self.order_imagery_dialog.raise_()
        self.order_imagery_dialog.activateWindow()
    
    def validate_license(self):
        """Validate license key and get JWT token."""
        license_key = self.licenseKeyLineEdit.text().strip()
        
        if not license_key:
            QtWidgets.QMessageBox.warning(
                self,
                "License Required",
                "Please enter a license key."
            )
            return
        
        # Disable button during validation
        self.validateLicenseButton.setEnabled(False)
        self.validateLicenseButton.setText("Validating...")
        self.licenseStatusLabel.setText("Validating...")
        self.licenseStatusLabel.setStyleSheet("color: blue;")
        
        # Call validation endpoint
        try:
            from .vec_inference_client import VecInferenceClient
            temp_client = VecInferenceClient(INFERENCE_BASE_URL)
            token, expiry = temp_client.validate_license_key(license_key)
            
            if token:
                self.jwt_token = token
                self.token_expiry = expiry
                self.license_key = license_key
                self.clear_trial_billable_idempotency_key()
                self.licenseStatusLabel.setText("✓ Valid")
                self.licenseStatusLabel.setStyleSheet("color: green;")
                self._update_trial_quota_label()

                # Enable OK button if polygon is drawn
                self._sync_ok_button_state()
            else:
                self.jwt_token = None
                self.token_expiry = None
                self.license_key = None
                self.licenseStatusLabel.setText("✗ Invalid")
                self.licenseStatusLabel.setStyleSheet("color: red;")
                self._update_trial_quota_label()
                self._sync_ok_button_state()
                QtWidgets.QMessageBox.warning(
                    self,
                    "Invalid License",
                    "The license key is invalid or expired."
                )
        except Exception as e:
            self.jwt_token = None
            self.token_expiry = None
            self.license_key = None
            self.licenseStatusLabel.setText("✗ Error")
            self.licenseStatusLabel.setStyleSheet("color: red;")
            self._update_trial_quota_label()
            self._sync_ok_button_state()
            QtWidgets.QMessageBox.critical(
                self,
                "Validation Error",
                f"Failed to validate license: {str(e)}"
            )
        finally:
            self.validateLicenseButton.setEnabled(True)
            self.validateLicenseButton.setText("Validate")
    
    def open_fieldwatch_website(self):
        """Open FieldWatch website for a full paid licence key (existing behaviour)."""
        QDesktopServices.openUrl(QUrl(FIELDWATCH_HOME_URL))

    def open_how_to_use_plugin_video(self):
        """Open the plugin walkthrough video (YouTube)."""
        QDesktopServices.openUrl(QUrl("https://youtu.be/F1vYdJV0_cs"))

    def open_feedback_dialog(self):
        """Open feedback modal; POSTs to /qgis/feedback (server sets submitted_at)."""
        dlg = FeedbackDialog(
            parent=self,
            install_key=self._install_key,
            trial_id=self._trial_id,
        )
        dlg.exec_()

    def start_polygon_drawing(self):
        """Start polygon drawing on the map canvas."""
        if not self.iface:
            QtWidgets.QMessageBox.warning(
                self,
                "Error",
                "Cannot draw polygon: QGIS interface not available."
            )
            return
        
        canvas = self.iface.mapCanvas()
        if not canvas:
            return
        
        # Store previous map tool
        self.previous_map_tool = canvas.mapTool()
        
        # Create custom polygon capture tool
        cad_dock = self.iface.cadDockWidget() if hasattr(self.iface, 'cadDockWidget') else None
        self.map_tool = PolygonCaptureTool(canvas, cad_dock)
        self.map_tool.finished.connect(self.polygon_finished)
        
        # Set as active tool
        canvas.setMapTool(self.map_tool)
        
        # Update UI
        self.drawPolygonButton.setEnabled(False)
        self.cropStatusValueLabel.setText("Drawing polygon... Click on map to add points, right-click to finish")
        self.cropStatusValueLabel.setStyleSheet("color: blue;")
        
        # Hide dialog temporarily so user can see the map
        self.hide()
    
    def polygon_finished(self, geometry):
        """Called when polygon drawing is finished."""
        if geometry and not geometry.isEmpty():
            self.crop_geometry = geometry
            self.polygon_drawn.emit(geometry)
        else:
            self.clear_polygon()
        
        # Restore previous map tool
        if self.iface and self.previous_map_tool:
            self.iface.mapCanvas().setMapTool(self.previous_map_tool)
        
        # Show dialog again
        self.show()
        self.raise_()
        self.activateWindow()
    
    def on_polygon_drawn(self, geometry):
        """Handle polygon drawn signal."""
        if geometry:
            # Get area info
            area = geometry.area()
            # Convert to readable format (assuming CRS units)
            if area > 1000000:
                area_str = f"{area/1000000:.2f} km²"
            elif area > 10000:
                area_str = f"{area/10000:.2f} ha"
            else:
                area_str = f"{area:.2f} m²"
            
            self.cropStatusValueLabel.setText(f"Area selected: {area_str}")
            self.cropStatusValueLabel.setStyleSheet("color: green;")
            self.clearPolygonButton.setEnabled(True)
            self.drawPolygonButton.setEnabled(True)
            
            # Enable OK when polygon is drawn and auth allows (paid JWT or active trial)
            self._sync_ok_button_state()
    
    def clear_polygon(self):
        """Clear the selected crop polygon."""
        self.crop_geometry = None
        self.cropStatusValueLabel.setText("No area selected - Please draw a polygon to continue")
        self.cropStatusValueLabel.setStyleSheet("color: red;")
        self.clearPolygonButton.setEnabled(False)
        self.drawPolygonButton.setEnabled(True)
        
        self.runButton.setEnabled(False)
    
    def accept(self):
        """Override accept to validate polygon is drawn and auth (paid or trial), then emit signal instead of closing."""
        if not self.jwt_token and not self.trial_can_run():
            QtWidgets.QMessageBox.warning(
                self,
                self.tr("License or trial required"),
                self.tr(
                    "Validate a paid license key, or wait until trial status shows remaining runs, "
                    "then try again."
                ),
            )
            return
        
        if not self.crop_geometry or self.crop_geometry.isEmpty():
            QtWidgets.QMessageBox.warning(
                self,
                "Polygon Required",
                "Please draw a polygon on the map before proceeding.\n\nClick 'Draw Polygon' and draw an area on the map canvas."
            )
            return

        # Trial billable attempt: one idempotency_key per OK click (checklist §5); reused if POST must retry.
        if not self.jwt_token and self.trial_can_run():
            if not self._trial_billable_idempotency_key:
                self._trial_billable_idempotency_key = str(uuid.uuid4())[:128]

        # Emit signal to start processing (dialog stays open)
        self.processing_started.emit()
        
        # Restore previous map tool if drawing was active
        if self.map_tool and self.iface:
            canvas = self.iface.mapCanvas()
            if canvas.mapTool() == self.map_tool:
                if self.previous_map_tool:
                    canvas.setMapTool(self.previous_map_tool)
                else:
                    canvas.unsetMapTool(self.map_tool)
    
    def closeEvent(self, event):
        """Handle dialog close event."""
        # Clear polygon drawing if active
        if self.map_tool and self.iface:
            canvas = self.iface.mapCanvas()
            if canvas.mapTool() == self.map_tool:
                if self.previous_map_tool:
                    canvas.setMapTool(self.previous_map_tool)
                else:
                    canvas.unsetMapTool(self.map_tool)
        super(VecPluginDialog, self).closeEvent(event)

    def _refresh_plugin_state(self):
        """
        Reset the main dialog and related state so it behaves like a fresh open.
        """
        # 1) Reset crop polygon and status
        try:
            self.clear_polygon()
        except Exception:
            pass

        # 2) Repopulate input layers
        try:
            self.populate_layers()
        except Exception:
            pass

        # 3) Reset status / progress
        try:
            self.statusLabel.setText("Ready")
        except Exception:
            pass
        try:
            self.progressBar.setVisible(False)
            self.progressBar.setValue(0)
        except Exception:
            pass

        # Disable OK until polygon + auth again
        self._sync_ok_button_state()

        # 5) Reset / recreate the Order Imagery dialog so it opens fresh next time
        if self.order_imagery_dialog is not None:
            try:
                self.order_imagery_dialog.close()
            except Exception:
                pass
            self.order_imagery_dialog = None

        # 6) Refresh trial quota from server
        QtCore.QTimer.singleShot(0, self.refresh_trial_state)

        self.clear_trial_billable_idempotency_key()
