# -*- coding: utf-8 -*-
"""
/***************************************************************************
 VecPluginDialog
                                 A QGIS plugin
 Integration with VEC inference service for building detection
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-12-09
        git sha              : $Format:%H$
        copyright            : (C) 2025 FieldWatch AI
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

import uuid

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets, QtCore, QtGui
from qgis.PyQt.QtCore import QUrl
from qgis.PyQt.QtGui import QDesktopServices
from qgis.core import QgsProject, QgsGeometry, QgsWkbTypes, QgsPointXY, QgsMessageLog, Qgis
from qgis.gui import QgsMapToolCapture, QgsRubberBand
from .order_imagery_dialog import OrderImageryDialog
from .feedback_dialog import FeedbackDialog
from ..core.api_config import INFERENCE_BASE_URL
from ..core import trial_helpers
from ..core.qt_compat import (
    LeftButton,
    PointingHandCursor,
    RightButton,
    RightToLeft,
    dialog_exec,
    red as qt_red,
)
from ..core.trial_access import shared as trial_shared
from ..core.trial_workers import TrialGenerateWorker, TrialStateFetchWorker
from ..core.onboarding_helpers import (
    prompt_onboarding_if_needed,
    require_onboarding,
    set_process_button_enabled,
    show_onboarding_dialog,
)

# Browser destination for paid licence keys.
FIELDWATCH_HOME_URL = "https://usefieldwatch.com/"

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), '..', 'ui', 'vec_plugin_dialog_base.ui'))

_PAGE_LANDING = 0
_PAGE_ONE_CLICK = 1
_PAGE_VECTORIZATION = 2
_PAGE_OBSTACLE_REMOVAL = 3

_LANDING_ACTION_STYLE = (
    "QPushButton {"
    " text-align: left;"
    " padding: 12px 14px 12px 16px;"
    " font-size: 13px;"
    " border: 1px solid palette(mid);"
    " border-radius: 4px;"
    "}"
    "QPushButton:hover { background: palette(alternate-base); }"
)
_LANDING_ICON_SIZE = QtCore.QSize(28, 28)


class PolygonCaptureTool(QgsMapToolCapture):
    """Custom map tool for capturing polygon geometry."""
    
    finished = QtCore.pyqtSignal(QgsGeometry)
    
    def __init__(self, canvas, cad_dock_widget=None):
        super(PolygonCaptureTool, self).__init__(canvas, cad_dock_widget, QgsMapToolCapture.CapturePolygon)
        self.canvas = canvas
        self.points = []
        self.rubber_band = None
    
    def canvasReleaseEvent(self, event):
        """Handle mouse release events."""
        if event.button() == RightButton:
            # Right click finishes the polygon
            if len(self.points) >= 3:
                # Create polygon from points
                polygon_points = self.points + [self.points[0]]  # Close polygon
                geometry = QgsGeometry.fromPolygonXY([polygon_points])
                self.finished.emit(geometry)
            else:
                # Not enough points
                self.finished.emit(QgsGeometry())
            self._cleanup_rubber_band()
            self.points = []
        elif event.button() == LeftButton:
            # Left click adds a point
            point = self.toMapCoordinates(event.pos())
            self.points.append(QgsPointXY(point))
            # Draw temporary rubber band
            if self.rubber_band is None:
                self.rubber_band = QgsRubberBand(self.canvas, QgsWkbTypes.PolygonGeometry)
                self.rubber_band.setColor(qt_red)
                self.rubber_band.setWidth(2)
                # Match order imagery dialog styling: semi-transparent red fill
                self.rubber_band.setFillColor(QtGui.QColor(255, 0, 0, 60))
            if len(self.points) > 1:
                self.rubber_band.reset(QgsWkbTypes.PolygonGeometry)
                for p in self.points:
                    self.rubber_band.addPoint(p, False)
                self.rubber_band.addPoint(self.points[0], True)  # Close polygon
                self.rubber_band.show()
    
    def _cleanup_rubber_band(self):
        """Clean up rubber band."""
        if self.rubber_band:
            self.rubber_band.reset()
            self.rubber_band = None
    
    def deactivate(self):
        """Clean up when tool is deactivated."""
        self._cleanup_rubber_band()
        self.points = []
        super(PolygonCaptureTool, self).deactivate()


class VecPluginDialog(QtWidgets.QDialog, FORM_CLASS):
    # Signal emitted when polygon is drawn
    polygon_drawn = QtCore.pyqtSignal(QgsGeometry)
    # Signal emitted when Run is clicked (but dialog stays open)
    processing_started = QtCore.pyqtSignal()
    # Open one-click segmentation settings (small window)
    one_click_requested = QtCore.pyqtSignal()
    # Open AI Obstacle Removal (nano banana edit)
    obstacle_removal_requested = QtCore.pyqtSignal()
    
    def __init__(self, parent=None, iface=None):
        """Constructor."""
        super(VecPluginDialog, self).__init__(parent)
        self.iface = iface
        self.crop_geometry = None
        self.map_tool = None
        self.previous_map_tool = None
        self.order_imagery_dialog = None
        self._returning_from_polygon_draw = False
        
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        
        # Trial + licence (shared profile state via trial_access)
        self._trial_acc = trial_shared()
        self._install_key = self._trial_acc.install_key
        self._trial_id = self._trial_acc.trial_id
        self.trial_uses_total = self._trial_acc.uses_total
        self.trial_uses_remaining = self._trial_acc.uses_remaining
        self.trial_status = self._trial_acc.trial_status
        self._trial_billable_idempotency_key = None
        self.license_key = self._trial_acc.license_key
        self.jwt_token = self._trial_acc.jwt_token
        self.token_expiry = self._trial_acc.token_expiry
        self._trial_state_worker = None
        self._trial_generate_worker = None
        self._trial_refresh_show_error_dialog = False
        self._trial_refresh_show_success_dialog = False

        self.trialQuotaLabel = QtWidgets.QLabel("")
        self.trialQuotaLabel.setWordWrap(True)
        self._trial_quota_spinner = QtWidgets.QProgressBar()
        self._trial_quota_spinner.setRange(0, 0)
        self._trial_quota_spinner.setFixedWidth(100)
        self._trial_quota_spinner.setFixedHeight(14)
        self._trial_quota_spinner.setTextVisible(False)
        self._trial_quota_spinner.setVisible(False)
        self.trialQuotaContainer = QtWidgets.QWidget()
        _quota_row = QtWidgets.QHBoxLayout(self.trialQuotaContainer)
        _quota_row.setContentsMargins(0, 0, 0, 0)
        _quota_row.addWidget(self._trial_quota_spinner)
        _quota_row.addWidget(self.trialQuotaLabel, 1)
        self.licenseFormLayout.addRow(
            QtWidgets.QLabel(self.tr("Trial quota:")),
            self.trialQuotaContainer,
        )

        self._setup_page_navigation()

        trial_helpers.maybe_migrate_legacy_onboarding()

        # Populate the input layer combo box with raster layers
        self.populate_layers()
        
        # Set default output layer name
        self.outputLayerLineEdit.setText("Building_Detections")
        if hasattr(self, "detectionTypeCombo"):
            self.detectionTypeCombo.setCurrentText("Building")
        
        # Hide progress bar initially
        self.progressBar.setVisible(False)
        
        # Connect polygon drawing buttons
        self.drawPolygonButton.clicked.connect(self.start_polygon_drawing)
        self.clearPolygonButton.clicked.connect(self.clear_polygon)
        
        # Connect license validation button
        self.validateLicenseButton.clicked.connect(self.validate_license)
        
        # CTA button: shown only when a paid licence is needed.
        self.getLicenseKeyButton.clicked.connect(self._on_license_action_clicked)
        self._update_license_action_button()

        # Connect signal
        self.polygon_drawn.connect(self.on_polygon_drawn)

        # Disable Run until polygon is drawn AND (paid JWT or active trial)
        self.runButton.setEnabled(False)
        self.runButton.setDefault(True)

        self._show_initial_page()

    @staticmethod
    def _landing_workflow_icon(filename):
        """Icon for a landing workflow button (Qt resource, else plugin folder PNG)."""
        resource_path = f":/plugins/vec_plugin/icons/{filename}"
        icon = QtGui.QIcon(resource_path)
        if not icon.isNull():
            return icon
        file_path = os.path.join(
            os.path.dirname(__file__), '..', 'resources', 'icons', filename
        )
        if os.path.isfile(file_path):
            return QtGui.QIcon(file_path)
        return QtGui.QIcon()

    def _setup_page_navigation(self):
        """Landing hub + workflow pages (stacked); footer actions only on landing."""
        self._stack = QtWidgets.QStackedWidget()

        # --- Landing ---
        self._page_landing = QtWidgets.QWidget()
        landing_layout = QtWidgets.QVBoxLayout(self._page_landing)
        landing_layout.setContentsMargins(28, 28, 28, 20)
        landing_layout.setSpacing(20)

        title = QtWidgets.QLabel(self.tr("The FieldWatch Pack."))
        title.setStyleSheet("font-size: 18px; font-weight: bold;")
        landing_layout.addWidget(title)

        welcome = QtWidgets.QLabel(self.tr("Hello, welcome."))
        welcome.setStyleSheet("font-size: 14px;")
        landing_layout.addWidget(welcome)

        subtitle = QtWidgets.QLabel(
            self.tr("How can we make your workflow better?")
        )
        subtitle.setWordWrap(True)
        subtitle.setStyleSheet("font-size: 14px;")
        landing_layout.addWidget(subtitle)
        landing_layout.addSpacing(8)

        self._btn_one_click = QtWidgets.QPushButton(self.tr("One-Click Segmentation"))
        self._btn_large_area = QtWidgets.QPushButton(self.tr("Large Area Vectorization"))
        self._btn_obstacle_removal = QtWidgets.QPushButton(
            self.tr("AI Imagery Edit")
        )
        self._btn_order_imagery = QtWidgets.QPushButton(self.tr("Order Drone Imagery"))
        _landing_icons = (
            (self._btn_one_click, "click.png"),
            (self._btn_large_area, "map.png"),
            (self._btn_obstacle_removal, "map.png"),
            (self._btn_order_imagery, "drone.png"),
        )
        for btn, icon_file in _landing_icons:
            btn.setStyleSheet(_LANDING_ACTION_STYLE)
            btn.setCursor(PointingHandCursor)
            icon = self._landing_workflow_icon(icon_file)
            if not icon.isNull():
                btn.setIcon(icon)
                btn.setIconSize(_LANDING_ICON_SIZE)
                btn.setLayoutDirection(RightToLeft)
            landing_layout.addWidget(btn)

        self._landingGetLicenceButton = QtWidgets.QPushButton(self.tr("Get Licence"))
        self._landingGetLicenceButton.setSizePolicy(self.getLicenseKeyButton.sizePolicy())
        self._landingGetLicenceButton.setToolTip(
            self.tr("Open FieldWatch in your browser to get a paid licence key.")
        )
        landing_layout.addWidget(self._landingGetLicenceButton)

        landing_layout.addStretch()

        landing_footer = QtWidgets.QHBoxLayout()
        landing_footer.setSpacing(10)
        self.howToUsePluginButton = QtWidgets.QPushButton(self.tr("How to use this plugin"))
        self.sendFeedbackButton = QtWidgets.QPushButton(self.tr("Send feedback"))
        self.termsButton = QtWidgets.QPushButton(self.tr("Terms"))
        self.termsButton.setToolTip(
            self.tr("Enter your email and accept the terms and conditions.")
        )
        landing_footer.addWidget(self.howToUsePluginButton)
        landing_footer.addWidget(self.sendFeedbackButton)
        landing_footer.addStretch()
        landing_footer.addWidget(self.termsButton)
        landing_layout.addLayout(landing_footer)

        self._landingGetLicenceButton.clicked.connect(self.open_fieldwatch_website)
        self._btn_one_click.clicked.connect(self.one_click_requested.emit)
        self._btn_large_area.clicked.connect(lambda: self._show_page(_PAGE_VECTORIZATION))
        self._btn_obstacle_removal.clicked.connect(
            self.obstacle_removal_requested.emit
        )
        self._btn_order_imagery.clicked.connect(self.open_order_imagery_dialog)
        self.howToUsePluginButton.clicked.connect(self.open_how_to_use_plugin_video)
        self.sendFeedbackButton.clicked.connect(self.open_feedback_dialog)
        self.termsButton.clicked.connect(self._open_onboarding_from_terms)

        # --- One-click placeholder ---
        self._page_one_click = QtWidgets.QWidget()
        one_click_layout = QtWidgets.QVBoxLayout(self._page_one_click)
        one_click_layout.setContentsMargins(24, 24, 24, 16)
        one_click_layout.setSpacing(12)

        oc_title = QtWidgets.QLabel(self.tr("One-Click Segmentation"))
        oc_title.setStyleSheet("font-size: 16px; font-weight: bold;")
        one_click_layout.addWidget(oc_title)

        oc_body = QtWidgets.QLabel(
            self.tr(
                "Trial runs are available automatically. Open map tools (or validate a paid licence if needed)."
            )
        )
        oc_body.setWordWrap(True)
        oc_body.setStyleSheet("color: palette(mid);")
        one_click_layout.addWidget(oc_body)

        self._openOneClickButton = QtWidgets.QPushButton(self.tr("Open segmentation"))
        self._openOneClickButton.setStyleSheet(_LANDING_ACTION_STYLE)
        self._openOneClickButton.setCursor(PointingHandCursor)
        one_click_layout.addWidget(self._openOneClickButton)
        one_click_layout.addStretch()

        one_click_footer = QtWidgets.QHBoxLayout()
        self.backFromOneClickButton = QtWidgets.QPushButton(self.tr("Back"))
        one_click_footer.addWidget(self.backFromOneClickButton)
        one_click_footer.addStretch()
        one_click_layout.addLayout(one_click_footer)
        self.backFromOneClickButton.clicked.connect(lambda: self._show_page(_PAGE_LANDING))
        self._openOneClickButton.clicked.connect(self.one_click_requested.emit)

        # --- Large area vectorization (existing form) ---
        self._page_vectorization = QtWidgets.QWidget()
        vec_layout = QtWidgets.QVBoxLayout(self._page_vectorization)
        vec_layout.setContentsMargins(0, 0, 0, 0)
        vec_layout.setSpacing(8)

        self.licenseGroupBox.setParent(None)

        for widget in (
            self.inputGroupBox,
            self.outputGroupBox,
            self.progressBar,
            self.statusLabel,
        ):
            widget.setParent(None)
            vec_layout.addWidget(widget)

        vec_footer = QtWidgets.QHBoxLayout()
        self.backFromVectorizationButton = QtWidgets.QPushButton(self.tr("Back"))
        self.refreshButton = QtWidgets.QPushButton(self.tr("Refresh"))
        self.runButton = QtWidgets.QPushButton(self.tr("Run"))
        self.cancelButton = QtWidgets.QPushButton(self.tr("Cancel"))
        vec_footer.addWidget(self.backFromVectorizationButton)
        vec_footer.addWidget(self.refreshButton)
        vec_footer.addStretch()
        vec_footer.addWidget(self.runButton)
        vec_footer.addWidget(self.cancelButton)
        vec_layout.addLayout(vec_footer)

        self.backFromVectorizationButton.clicked.connect(lambda: self._show_page(_PAGE_LANDING))
        self.refreshButton.clicked.connect(self._refresh_plugin_state)
        self.runButton.clicked.connect(self.accept)
        self.cancelButton.clicked.connect(self.reject)

        self._stack.addWidget(self._page_landing)
        self._stack.addWidget(self._page_one_click)
        self._stack.addWidget(self._page_vectorization)

        while self.verticalLayout.count():
            self.verticalLayout.takeAt(0)
        self.verticalLayout.addWidget(self._stack)

        self.resize(500, 580)

    def _place_license_panel(self, page_widget, insert_index=0):
        """Shared licence + trial quota panel on workflow pages only."""
        layout = page_widget.layout()
        if layout is None:
            return
        for i in range(layout.count()):
            item = layout.itemAt(i)
            if item and item.widget() is self.licenseGroupBox:
                layout.removeWidget(self.licenseGroupBox)
                break
        self.licenseGroupBox.setParent(None)
        layout.insertWidget(insert_index, self.licenseGroupBox)
        self.licenseGroupBox.show()

    def _show_page(self, index):
        self._stack.setCurrentIndex(index)
        titles = {
            _PAGE_LANDING: self.tr("The FieldWatch Pack."),
            _PAGE_ONE_CLICK: self.tr("One-Click Segmentation"),
            _PAGE_VECTORIZATION: self.tr("Large Area Vectorization"),
        }
        self.setWindowTitle(titles.get(index, self.tr("The FieldWatch Pack.")))
        if index == _PAGE_VECTORIZATION:
            self._place_license_panel(self._page_vectorization, insert_index=0)
            self.populate_layers()
            self._update_trial_quota_label()
            self.resize(500, 620)
        elif index == _PAGE_ONE_CLICK:
            self.licenseGroupBox.hide()
            self.resize(440, 320)
        elif index == _PAGE_LANDING:
            self.licenseGroupBox.hide()
            self.resize(440, 360)
        else:
            self.resize(440, 280)

    def _show_initial_page(self):
        """Landing hub, or large-area page when returning from polygon draw."""
        if self._returning_from_polygon_draw:
            self._returning_from_polygon_draw = False
            self._show_page(_PAGE_VECTORIZATION)
        else:
            self._show_page(_PAGE_LANDING)

    def showEvent(self, event):
        """Show landing; prompt onboarding for new users; sync trial when complete."""
        super(VecPluginDialog, self).showEvent(event)
        self._show_initial_page()
        self._sync_ui_from_trial_access()
        if trial_helpers.is_onboarding_complete():
            self._trial_acc.sync_pending_usages()
            QtCore.QTimer.singleShot(0, self.refresh_trial_state)
        else:
            QtCore.QTimer.singleShot(0, self._prompt_onboarding_on_open)

    def _prompt_onboarding_on_open(self):
        prompt_onboarding_if_needed(
            self,
            self._install_key,
            on_registered=self._after_onboarding_registered,
        )
        self._sync_ok_button_state()

    def _open_onboarding_from_terms(self):
        show_onboarding_dialog(
            self,
            self._install_key,
            on_registered=self._after_onboarding_registered,
        )
        self._sync_ok_button_state()

    def _sync_ui_from_trial_access(self):
        acc = self._trial_acc
        self._install_key = acc.install_key
        self._trial_id = acc.trial_id
        self.trial_uses_total = acc.uses_total
        self.trial_uses_remaining = acc.uses_remaining
        self.trial_status = acc.trial_status
        self.jwt_token = acc.jwt_token
        self.license_key = acc.license_key
        self.token_expiry = acc.token_expiry
        if acc.license_key and hasattr(self, "licenseKeyLineEdit"):
            if not self.licenseKeyLineEdit.text().strip():
                self.licenseKeyLineEdit.setText(acc.license_key)
        self._update_trial_quota_label()

    def _push_ui_to_trial_access(self):
        acc = self._trial_acc
        acc.trial_id = self._trial_id
        acc.uses_total = self.trial_uses_total
        acc.uses_remaining = self.trial_uses_remaining
        acc.trial_status = self.trial_status

    def _set_trial_quota_loading(self, loading):
        self._trial_quota_spinner.setVisible(bool(loading))
        if loading:
            self.trialQuotaLabel.setText(self.tr("Loading trial status…"))
            self.trialQuotaLabel.setStyleSheet("color: blue;")

    def populate_layers(self):
        """Populate the input layer combo box with available raster layers."""
        self.inputLayerCombo.clear()
        
        # Get all layers from the project
        layers = QgsProject.instance().mapLayers().values()
        
        # Filter for raster layers
        raster_layers = [layer for layer in layers if layer.type() == 1]  # 1 = raster layer
        
        if raster_layers:
            for layer in raster_layers:
                self.inputLayerCombo.addItem(layer.name(), layer)
            # Explicitly enable the combo box when layers are found
            self.inputLayerCombo.setEnabled(True)
        else:
            self.inputLayerCombo.addItem("No raster layers available", None)
            self.inputLayerCombo.setEnabled(False)
    
    def get_input_layer(self):
        """Get the selected input raster layer."""
        if self.inputLayerCombo.currentData():
            return self.inputLayerCombo.currentData()
        return None
    
    def get_output_layer_name(self):
        """Get the output layer name."""
        name = self.outputLayerLineEdit.text().strip()
        if not name:
            return "Building_Detections"
        return name
    
    def get_crop_geometry(self):
        """Get the crop polygon geometry."""
        return self.crop_geometry

    def get_detection_type(self):
        """Get selected detection type."""
        if hasattr(self, "detectionTypeCombo"):
            text = self.detectionTypeCombo.currentText().strip().lower()
            return "solar_panel" if text == "solar panel" else "building"
        return "building"
    
    def get_license_key(self):
        """Get the license key."""
        return self.license_key
    
    def get_jwt_token(self):
        """Get the JWT token."""
        return self.jwt_token

    def _has_paid_auth(self):
        """Paid path requires both a validated licence key and JWT in settings."""
        return bool((self.jwt_token or "").strip() and (self.license_key or "").strip())

    def get_install_key(self):
        return self._install_key

    def get_trial_id(self):
        return self._trial_id

    def trial_can_run(self):
        """True if established trial can start a billable run (paid JWT elsewhere)."""
        if self._has_paid_auth():
            return False
        return self._trial_acc.is_trial_unlocked()

    def _license_action_is_generate_trial(self):
        """Trial is auto-bootstrapped; never expose a user "generate trial key" action."""
        return False

    def _update_license_action_button(self):
        """Show "Get Licence" only after trial is exhausted/revoked (or paid validation is needed)."""
        if not hasattr(self, "getLicenseKeyButton"):
            return
        # Hide CTA while paid or while active trial is available.
        if self._has_paid_auth() or self.trial_can_run():
            self.getLicenseKeyButton.setVisible(False)
            return

        # While state is unknown, keep CTA hidden (spinner/label will explain).
        if self.trial_status is None and self.trial_uses_remaining is None:
            self.getLicenseKeyButton.setVisible(False)
            return

        # Show CTA when the trial is clearly exhausted/revoked/zero.
        trial_exhausted = (
            self.trial_status in ("exhausted", "revoked")
            or (self.trial_uses_remaining is not None and self.trial_uses_remaining <= 0)
        )
        if not trial_exhausted:
            self.getLicenseKeyButton.setVisible(False)
            return

        self.getLicenseKeyButton.setVisible(True)
        self.getLicenseKeyButton.setText(self.tr("Get Licence"))
        self.getLicenseKeyButton.setToolTip(
            self.tr("Open FieldWatch in your browser to get a paid licence key.")
        )
        self.getLicenseKeyButton.setEnabled(True)

    def _on_license_action_clicked(self):
        # UX: only paid CTA is exposed after trial exhaustion.
        self.open_fieldwatch_website()

    def _update_trial_quota_label(self):
        if self._has_paid_auth():
            self.trialQuotaLabel.setText(
                self.tr("Using paid license — runs use your key, not trial quota.")
            )
            self.trialQuotaLabel.setStyleSheet("color: gray;")
        elif not trial_helpers.is_trial_established():
            self.trialQuotaLabel.setText(self.tr("Loading trial status…"))
            self.trialQuotaLabel.setStyleSheet("color: blue;")
        elif self.trial_status is None and self.trial_uses_remaining is None:
            if self._trial_quota_spinner.isVisible():
                self.trialQuotaLabel.setText(self.tr("Loading trial status…"))
                self.trialQuotaLabel.setStyleSheet("color: blue;")
            else:
                self.trialQuotaLabel.setText("")
                self.trialQuotaLabel.setStyleSheet("color: gray;")
        else:
            total = self.trial_uses_total
            rem = self.trial_uses_remaining
            if total is not None and rem is not None:
                used = max(0, total - rem)
                txt = self.tr("{0} of {1} trial runs remaining (used {2}).").format(rem, total, used)
            elif rem is not None:
                txt = self.tr("{0} trial runs remaining.").format(rem)
            else:
                txt = self.tr("Trial status: {0}").format(self.trial_status or "unknown")
            if self.trial_status == "exhausted" or (rem is not None and rem <= 0):
                self.trialQuotaLabel.setStyleSheet("color: red;")
                txt += " " + self.tr("Register for a full license key at usefieldwatch.com.")
            elif self.trial_status == "revoked":
                self.trialQuotaLabel.setStyleSheet("color: red;")
            else:
                self.trialQuotaLabel.setStyleSheet("color: green;")
            self.trialQuotaLabel.setText(txt)

        # Trial-only UX: hide paid licence inputs while trial is active.
        trial_exhausted = (
            self.trial_status in ("exhausted", "revoked")
            or (self.trial_uses_remaining is not None and self.trial_uses_remaining <= 0)
        )
        show_inputs = (not self._has_paid_auth()) and trial_exhausted
        if hasattr(self, "licenseKeyLineEdit"):
            self.licenseKeyLineEdit.setVisible(show_inputs)
        if hasattr(self, "validateLicenseButton"):
            self.validateLicenseButton.setVisible(show_inputs)
        self._update_license_action_button()

    def refresh_trial_state(self, show_error_dialog=False, show_success_dialog=False):
        """Refresh trial quota from the server in a background thread."""
        self._trial_refresh_show_error_dialog = show_error_dialog
        self._trial_refresh_show_success_dialog = show_success_dialog
        if self._trial_state_worker is not None and self._trial_state_worker.isRunning():
            return
        if self._trial_generate_worker is not None and self._trial_generate_worker.isRunning():
            return
        self._set_trial_quota_loading(True)
        # UX: if this is a first-time profile, auto bootstrap trial (no user clicks).
        if not trial_helpers.is_trial_established():
            self._trial_generate_worker = TrialGenerateWorker(self._install_key, parent=self)
            self._trial_generate_worker.finished_ok.connect(self._on_trial_generated)
            self._trial_generate_worker.failed.connect(self._on_trial_generate_failed)
            self._trial_generate_worker.finished.connect(self._on_trial_generate_worker_finished)
            self._trial_generate_worker.start()
        else:
            self._trial_state_worker = TrialStateFetchWorker(self._install_key, self._trial_id)
            self._trial_state_worker.finished_ok.connect(self._on_trial_state_fetched)
            self._trial_state_worker.failed.connect(self._on_trial_state_fetch_failed)
            self._trial_state_worker.finished.connect(self._on_trial_state_worker_finished)
            self._trial_state_worker.start()

    def generate_trial_key(self, show_error_dialog=False, show_success_dialog=True):
        """Request a new trial key from the server for this profile."""
        self._trial_refresh_show_error_dialog = show_error_dialog
        self._trial_refresh_show_success_dialog = show_success_dialog
        if self._trial_generate_worker is not None and self._trial_generate_worker.isRunning():
            return
        if self._trial_state_worker is not None and self._trial_state_worker.isRunning():
            return
        self._set_trial_quota_loading(True)
        self.getLicenseKeyButton.setEnabled(False)
        self._trial_generate_worker = TrialGenerateWorker(self._install_key, parent=self)
        self._trial_generate_worker.finished_ok.connect(self._on_trial_generated)
        self._trial_generate_worker.failed.connect(self._on_trial_generate_failed)
        self._trial_generate_worker.finished.connect(self._on_trial_generate_worker_finished)
        self._trial_generate_worker.start()

    def _on_trial_generate_worker_finished(self):
        self._trial_generate_worker = None
        self._update_license_action_button()

    def _show_trial_generate_success(self, data: dict) -> None:
        trial_helpers.mark_trial_established()
        tid = trial_helpers.trial_id_from_response(data) or (self._trial_id or "")
        if tid:
            self.licenseKeyLineEdit.setText(tid)
            QtWidgets.QApplication.clipboard().setText(tid)
            trial_helpers.set_trial_generate_locked_trial_id(tid)
            self.licenseStatusLabel.setText(self.tr("✓ Trial key generated"))
            self.licenseStatusLabel.setStyleSheet("color: green;")
        rem = data.get("uses_remaining")
        tot = data.get("uses_total")
        rem_s = str(rem) if rem is not None else "?"
        tot_s = str(tot) if tot is not None else "?"
        if tid:
            body = self.tr(
                "Your trial key:\n\n{0}\n\n"
                "Runs remaining: {1} of {2}.\n\n"
                "The key has been copied to the clipboard and filled in above."
            ).format(tid, rem_s, tot_s)
        else:
            body = self.tr(
                "Trial activated.\n\nRuns remaining: {0} of {1}."
            ).format(rem_s, tot_s)
        QtWidgets.QMessageBox.information(self, self.tr("Trial key"), body)

    def _on_trial_generated(self, data):
        self._set_trial_quota_loading(False)
        self._trial_acc.apply_server_state(data)
        self._sync_ui_from_trial_access()
        self._sync_ok_button_state()
        if trial_helpers.trial_id_from_response(data) and not trial_helpers.is_trial_established():
            trial_helpers.mark_trial_established()
        if self._trial_refresh_show_success_dialog:
            self._show_trial_generate_success(data)

    def _on_trial_generate_failed(self, err_text):
        self._set_trial_quota_loading(False)
        self.trialQuotaLabel.setText(self.tr("Could not generate trial key."))
        self.trialQuotaLabel.setStyleSheet("color: red;")
        if self._trial_refresh_show_error_dialog:
            QtWidgets.QMessageBox.warning(
                self, self.tr("Trial key"), err_text[:2000]
            )
        self._update_license_action_button()

    def _on_trial_state_worker_finished(self):
        self._trial_state_worker = None

    def _on_trial_state_fetched(self, data):
        self._set_trial_quota_loading(False)
        self._trial_acc.apply_server_state(data)
        self._sync_ui_from_trial_access()
        self._sync_ok_button_state()
        if trial_helpers.trial_id_from_response(data) and not trial_helpers.is_trial_established():
            trial_helpers.mark_trial_established()

    def _on_trial_state_fetch_failed(self, _err_text):
        self._set_trial_quota_loading(False)
        show_error_dialog = self._trial_refresh_show_error_dialog
        self.trial_status = None
        _trial_err_msg = self.tr(
            "Could not load trial status. you can still validate a paid license."
        )
        self.trialQuotaLabel.setText(_trial_err_msg)
        self.trialQuotaLabel.setStyleSheet("color: orange;")
        QgsMessageLog.logMessage(
            f"Trial state refresh: {_err_text}",
            "VEC Plugin",
            Qgis.Warning,
        )
        if show_error_dialog:
            QtWidgets.QMessageBox.warning(
                self,
                self.tr("Trial status"),
                _trial_err_msg,
            )
        self._update_license_action_button()

    def apply_trial_usage_response(self, data):
        """Update UI after a successful trial usage debit (allowed path)."""
        self._trial_acc.apply_server_state(data)
        self._sync_ui_from_trial_access()
        self._sync_ok_button_state()

    def _sync_ok_button_state(self):
        has_polygon = bool(self.crop_geometry and not self.crop_geometry.isEmpty())
        auth_ok = self._has_paid_auth() or self.trial_can_run()
        set_process_button_enabled(self.runButton, has_polygon and auth_ok)

    def apply_trial_usage_denied(self, data):
        """Update UI after usage denied."""
        self._trial_acc.apply_server_state(data)
        self._sync_ui_from_trial_access()
        self._sync_ok_button_state()

    def get_trial_billable_idempotency_key(self):
        """Stable idempotency key for the current billable run (max 128 chars)."""
        key = self._trial_acc.get_billable_idempotency_key()
        self._trial_billable_idempotency_key = key
        return key

    def clear_trial_billable_idempotency_key(self):
        """Clear after trial usage debit completes (HTTP response received)."""
        self._trial_acc.clear_billable_idempotency_key()
        self._trial_billable_idempotency_key = None

    def open_order_imagery_dialog(self):
        """Open the Order drone imagery dialog."""
        if not self.iface:
            QtWidgets.QMessageBox.warning(
                self,
                "Error",
                "Cannot open order dialog: QGIS interface not available."
            )
            return
        
        if self.order_imagery_dialog is None:
            self.order_imagery_dialog = OrderImageryDialog(iface=self.iface, parent=self)
        
        self.order_imagery_dialog.show()
        self.order_imagery_dialog.raise_()
        self.order_imagery_dialog.activateWindow()

    @staticmethod
    def _looks_like_trial_uuid(text):
        """True if text is a canonical UUID string (server trial_id shape)."""
        try:
            uuid.UUID(str(text).strip())
            return True
        except (ValueError, TypeError, AttributeError):
            return False

    def _validate_pasted_trial_id(self, license_key):
        """Validate a pasted trial UUID against the server (not paid licence validation)."""
        self.validateLicenseButton.setEnabled(False)
        self.validateLicenseButton.setText(self.tr("Validating…"))
        self.licenseStatusLabel.setText(self.tr("Validating trial key…"))
        self.licenseStatusLabel.setStyleSheet("color: blue;")

        old_tid = self._trial_id
        self._trial_acc.clear_paid_license()

        try:
            tid = str(uuid.UUID(license_key.strip()))
            self._trial_id = tid
            trial_helpers.set_stored_trial_id(tid)
            data = trial_helpers.fetch_trial_state(
                INFERENCE_BASE_URL,
                self._install_key,
                trial_id=tid,
                timeout=10,
            )
            self._trial_acc.apply_server_state(data)
            self._sync_ui_from_trial_access()
            self._sync_ok_button_state()

            if self.trial_can_run():
                trial_helpers.mark_trial_established()
                self.licenseStatusLabel.setText(self.tr("✓ Trial key valid"))
                self.licenseStatusLabel.setStyleSheet("color: green;")
            elif self.trial_status == "exhausted" or (
                self.trial_uses_remaining is not None and self.trial_uses_remaining <= 0
            ):
                self.licenseStatusLabel.setText(self.tr("✗ Trial exhausted"))
                self.licenseStatusLabel.setStyleSheet("color: red;")
                QtWidgets.QMessageBox.information(
                    self,
                    self.tr("Trial key"),
                    self.tr("This trial id has no runs left. Use Get Licence for a paid key."),
                )
            else:
                self.licenseStatusLabel.setText(
                    self.tr("✗ Trial not active ({0})").format(self.trial_status or "?")
                )
                self.licenseStatusLabel.setStyleSheet("color: red;")
        except Exception as e:
            self._trial_id = old_tid
            if old_tid:
                trial_helpers.set_stored_trial_id(old_tid)
            else:
                trial_helpers.clear_stored_trial_id()
            self.licenseStatusLabel.setText(self.tr("✗ Trial key invalid"))
            self.licenseStatusLabel.setStyleSheet("color: red;")
            self._update_trial_quota_label()
            self._sync_ok_button_state()
            QtWidgets.QMessageBox.warning(
                self,
                self.tr("Trial key"),
                self.tr(
                    "This value is not a valid trial key for this installation, "
                    "or the server rejected it.\n\nDetails:\n{0}"
                ).format(str(e)[:500]),
            )
        finally:
            self.validateLicenseButton.setEnabled(True)
            self.validateLicenseButton.setText(self.tr("Validate"))

    def validate_license(self):
        """Validate paid license key (JWT) or a pasted server trial id (UUID)."""
        license_key = self.licenseKeyLineEdit.text().strip()

        if not license_key:
            QtWidgets.QMessageBox.warning(
                self,
                "License Required",
                "Please enter a license key."
            )
            return

        if self._looks_like_trial_uuid(license_key):
            self._validate_pasted_trial_id(license_key)
            return

        # Disable button during validation
        self.validateLicenseButton.setEnabled(False)
        self.validateLicenseButton.setText("Validating...")
        self.licenseStatusLabel.setText("Validating...")
        self.licenseStatusLabel.setStyleSheet("color: blue;")
        
        # Call validation endpoint
        try:
            from ..core.vec_inference_client import VecInferenceClient
            temp_client = VecInferenceClient(INFERENCE_BASE_URL)
            token, expiry = temp_client.validate_license_key(license_key)
            
            if token:
                self._trial_acc.set_paid_license(token, license_key, expiry)
                self._sync_ui_from_trial_access()
                self.clear_trial_billable_idempotency_key()
                self.licenseStatusLabel.setText("✓ Valid")
                self.licenseStatusLabel.setStyleSheet("color: green;")
                self._update_trial_quota_label()

                # Enable OK button if polygon is drawn
                self._sync_ok_button_state()
            else:
                self._trial_acc.clear_paid_license()
                self._sync_ui_from_trial_access()
                self.licenseStatusLabel.setText("✗ Invalid")
                self.licenseStatusLabel.setStyleSheet("color: red;")
                self._update_trial_quota_label()
                self._sync_ok_button_state()
                QtWidgets.QMessageBox.warning(
                    self,
                    "Invalid License",
                    "The license key is invalid or expired."
                )
        except Exception as e:
            self._trial_acc.clear_paid_license()
            self._sync_ui_from_trial_access()
            self.licenseStatusLabel.setText("✗ Error")
            self.licenseStatusLabel.setStyleSheet("color: red;")
            self._update_trial_quota_label()
            self._sync_ok_button_state()
            QtWidgets.QMessageBox.critical(
                self,
                "Validation Error",
                f"Failed to validate license: {str(e)}"
            )
        finally:
            self.validateLicenseButton.setEnabled(True)
            self.validateLicenseButton.setText("Validate")
    
    def open_fieldwatch_website(self):
        """Open FieldWatch website for a full paid licence key (existing behaviour)."""
        QDesktopServices.openUrl(QUrl(FIELDWATCH_HOME_URL))

    def open_how_to_use_plugin_video(self):
        """Open the plugin walkthrough video (YouTube)."""
        QDesktopServices.openUrl(QUrl("https://youtu.be/F1vYdJV0_cs"))

    def open_feedback_dialog(self):
        """Open feedback modal; POSTs to /qgis/feedback (server sets submitted_at)."""
        dlg = FeedbackDialog(
            parent=self,
            install_key=self._install_key,
            trial_id=self._trial_id,
        )
        dialog_exec(dlg)

    def start_polygon_drawing(self):
        """Start polygon drawing on the map canvas."""
        if not self.iface:
            QtWidgets.QMessageBox.warning(
                self,
                "Error",
                "Cannot draw polygon: QGIS interface not available."
            )
            return
        
        canvas = self.iface.mapCanvas()
        if not canvas:
            return
        
        # Store previous map tool
        self.previous_map_tool = canvas.mapTool()
        
        # Create custom polygon capture tool
        cad_dock = self.iface.cadDockWidget() if hasattr(self.iface, 'cadDockWidget') else None
        self.map_tool = PolygonCaptureTool(canvas, cad_dock)
        self.map_tool.finished.connect(self.polygon_finished)
        
        # Set as active tool
        canvas.setMapTool(self.map_tool)
        
        # Update UI
        self.drawPolygonButton.setEnabled(False)
        self.cropStatusValueLabel.setText("Drawing polygon... Click on map to add points, right-click to finish")
        self.cropStatusValueLabel.setStyleSheet("color: blue;")
        
        # Hide dialog temporarily so user can see the map
        self._returning_from_polygon_draw = True
        self.hide()
    
    def polygon_finished(self, geometry):
        """Called when polygon drawing is finished."""
        if geometry and not geometry.isEmpty():
            self.crop_geometry = geometry
            self.polygon_drawn.emit(geometry)
        else:
            self.clear_polygon()
        
        # Restore previous map tool
        if self.iface and self.previous_map_tool:
            self.iface.mapCanvas().setMapTool(self.previous_map_tool)
        
        # Show dialog again
        self.show()
        self.raise_()
        self.activateWindow()
    
    def on_polygon_drawn(self, geometry):
        """Handle polygon drawn signal."""
        if geometry:
            # Get area info
            area = geometry.area()
            # Convert to readable format (assuming CRS units)
            if area > 1000000:
                area_str = f"{area/1000000:.2f} km²"
            elif area > 10000:
                area_str = f"{area/10000:.2f} ha"
            else:
                area_str = f"{area:.2f} m²"
            
            self.cropStatusValueLabel.setText(f"Area selected: {area_str}")
            self.cropStatusValueLabel.setStyleSheet("color: green;")
            self.clearPolygonButton.setEnabled(True)
            self.drawPolygonButton.setEnabled(True)
            
            # Enable OK when polygon is drawn and auth allows (paid JWT or active trial)
            self._sync_ok_button_state()
    
    def clear_polygon(self):
        """Clear the selected crop polygon."""
        self.crop_geometry = None
        self.cropStatusValueLabel.setText("No area selected - Please draw a polygon to continue")
        self.cropStatusValueLabel.setStyleSheet("color: red;")
        self.clearPolygonButton.setEnabled(False)
        self.drawPolygonButton.setEnabled(True)
        self._sync_ok_button_state()
    
    def accept(self):
        """Validate polygon, onboarding, then start processing."""
        if not self.crop_geometry or self.crop_geometry.isEmpty():
            QtWidgets.QMessageBox.warning(
                self,
                "Polygon Required",
                "Please draw a polygon on the map before proceeding.\n\nClick 'Draw Polygon' and draw an area on the map canvas."
            )
            return

        def _run_processing():
            if not self._has_paid_auth() and not self.trial_can_run():
                QtWidgets.QMessageBox.warning(
                    self,
                    self.tr("License or trial required"),
                    self.tr(
                        "Validate a paid licence key or wait for trial quota to load."
                    ),
                )
                return
            if not self._has_paid_auth() and self.trial_can_run():
                self.get_trial_billable_idempotency_key()
            self.processing_started.emit()
            if self.map_tool and self.iface:
                canvas = self.iface.mapCanvas()
                if canvas.mapTool() == self.map_tool:
                    if self.previous_map_tool:
                        canvas.setMapTool(self.previous_map_tool)
                    else:
                        canvas.unsetMapTool(self.map_tool)

        require_onboarding(
            self,
            self._install_key,
            _run_processing,
            on_registered=self._after_onboarding_registered,
        )

    def _after_onboarding_registered(self):
        self._sync_ui_from_trial_access()
        self._sync_ok_button_state()
        QtCore.QTimer.singleShot(0, self.refresh_trial_state)
    
    def closeEvent(self, event):
        """Handle dialog close event."""
        # Clear polygon drawing if active
        if self.map_tool and self.iface:
            canvas = self.iface.mapCanvas()
            if canvas.mapTool() == self.map_tool:
                if self.previous_map_tool:
                    canvas.setMapTool(self.previous_map_tool)
                else:
                    canvas.unsetMapTool(self.map_tool)
        super(VecPluginDialog, self).closeEvent(event)

    def _refresh_plugin_state(self):
        """
        Reset the main dialog and related state so it behaves like a fresh open.
        """
        # 1) Reset crop polygon and status
        try:
            self.clear_polygon()
        except Exception:
            pass

        # 2) Repopulate input layers
        try:
            self.populate_layers()
        except Exception:
            pass

        # 3) Reset status / progress
        try:
            self.statusLabel.setText("Ready")
        except Exception:
            pass
        try:
            self.progressBar.setVisible(False)
            self.progressBar.setValue(0)
        except Exception:
            pass

        # Disable OK until polygon + auth again
        self._sync_ok_button_state()

        # 5) Reset / recreate the Order Imagery dialog so it opens fresh next time
        if self.order_imagery_dialog is not None:
            try:
                self.order_imagery_dialog.close()
            except Exception:
                pass
            self.order_imagery_dialog = None

        # 6) Refresh trial quota from server
        QtCore.QTimer.singleShot(0, self.refresh_trial_state)

        self.clear_trial_billable_idempotency_key()

        self._show_page(_PAGE_LANDING)
